TYPO3:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: 'db_neos'
        user: 'admin'
        password: 'my-pass'
        host: 'db'
        port: 3306

  Imagine:
    driver: Imagick