Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: 'db_neos'
        user: 'admin'
        password: 'my-pass'
        host: 'db'
        port: 3306
    mvc:
      routes:
        'ObisConcept.NeosAjaxForm': TRUE
        'ObisConcept.NeosSearch': TRUE
  Imagine:
    driver: Imagick
