db:
  image: million12/mariadb:latest
  environment:
    - MARIADB_PASS=my-pass
web:
  build: ./docker-files/web
  ports:
    - "80:80"
    - "22:22"
  links:
    - db:db
  volumes:
    - ./dev/Packages/FlowSites:/var/www/neos/Packages/FlowSites
    - ./dev/Packages/FlowPlugins:/var/www/neos/Packages/FlowPlugins
    - ./dev/Configuration:/var/www/neos/Configuration
